name: Collabora Online Development Edition (CODE)
slug: collabora-code
description: Collabora Online Development Edition - an awesome, Online Office suite
  image suitable for home use.
url: https://github.com/matthiasbalke/addon-collabora-code
version: a334c37
stage: experimental
image: ghcr.io/matthiasbalke/collabora-code/{arch}
init: false
startup: services
arch:
- aarch64
- amd64
webui: https://[HOST]:[PORT:9980]/browser/dist/admin/admin.html
ports:
  9980/tcp: 9980
ports_description:
  9980/tcp: coolwsd server port
map:
- addon_config:rw
options:
  username: ''
  password: ''
  generate_ssl_certificate: false
  coolwsd_arguments: --o:logging.level=information --o:logging.color=false --o:ssl.enable=false
    --o:ssl.termination=true
schema:
  username: str
  password: password
  server_name: str?
  generate_ssl_certificate: bool
  coolwsd_arguments: str?
