---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

permissions:
  contents: read

concurrency:
  group: queue

jobs:
  publish:
    name: Publish app update
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Repository Updater
        # fix/config-writer-not-released-repository-version
        uses: matthiasbalke/repository-updater@7bc8c6f8e4e8f404f3c9bc2e016e94080fc614ac
        with:
          app: ${{ github.event.client_payload.app }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
